<div class="placeholder-div">
    <?php if ($this->isPlaceholderEnabled() && $this->getTitle() !== '') : ?>
        <div class="content-block">
            <div class="image">
                <img src="<?= $this->getImageUrl(); ?>" alt="Sample Image">
            </div>
            <div class="text">
                <div class="sub-section">
                    <h4> <?= $this->getTitle(); ?></h4>
                    <p> <?= $this->getParagraph(); ?></p>
                    <p><a href="https://google.com">Find out more</a></p>
                </div>
            </div>
        </div>
        <?php // echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('custom-placeholder')->toHtml(); ?>

    <?php endif; ?>

</div>


